import pygame

pygame.init()

#ALTO Y ANCHO DE LA PANTALLA DEL JUEGO
#RESOLUCION DINÁMICA PARA ACOMODAR LA RESOLUCION DE LA PANTALLA DE CADA USUARIO
info = pygame.display.Info()

ALTO_VENTANA = info.current_h-70
ANCHO_VENTANA = info.current_w

#COLORES
# Fondo
AZUL_CIELO = (135, 206, 235)
# Piso
VERDE_PASTO = (70, 160, 70)
# Panel lateral
PANEL_LATERAL = (35, 35, 45)
# Panel interno
PANEL_INTERNO = (50, 50, 65)
# Texto
BLANCO = (255, 255, 255)
NEGRO = (20, 20, 20)
# Trayectoria
AMARILLO = (255, 220, 0)
# Proyectil
ROJO = (255, 70, 70)
# Altura máxima
VERDE = (0, 255, 120)
# Alcance
NARANJA = (255, 140, 0)
# Bordes
BORDES = (90, 90, 110)
# Títulos
CYAN = (0, 255, 255)

#LA FRECUENCIA DE ACTUALIZACION
FPS = 60

#GRAVEDAD
GRAVEDAD = 9.8

#DATOS PROYECTIL
VELOCIDAD_INICIAL = 0
ANGULO = 45

#POSICION INICIAL
INICIAL_X = 50
INICIAL_Y = ANCHO_VENTANA-50

#TIEMPO
TIEMPO = 0

#ESTADO INICIAL DEL LANZAMIENTO
LANZADOR = False

#TRAYECTORIA: LISTA QUE ALMACENA LOS PUNTOS
TRAYECTORIA = []

#ESCALA
ESCALA_INICIAL = 10




